version: "3"
services:
  postgres:
    image: postgres:14 # Use the desired PostgreSQL version
    container_name: postgres_hyphen
    ports:
      - "5432:5432"  # Expose port 5432 to the host
    environment:
      POSTGRES_USER: postgres          # Set your desired username
      POSTGRES_PASSWORD: password  # Set your desired password
      POSTGRES_DB: hyphen        # Set your desired database name
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2 # Use the desired Redis version
    container_name: redis_hyphen
    ports:
      - "6379:6379"  # Expose port 6379 to the host
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:

